/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as FolioImport } from './routes/Folio'

// Create/Update Routes

const FolioRoute = FolioImport.update({
  id: '/Folio',
  path: '/Folio',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/Folio': {
      id: '/Folio'
      path: '/Folio'
      fullPath: '/Folio'
      preLoaderRoute: typeof FolioImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/Folio': typeof FolioRoute
}

export interface FileRoutesByTo {
  '/Folio': typeof FolioRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/Folio': typeof FolioRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/Folio'
  fileRoutesByTo: FileRoutesByTo
  to: '/Folio'
  id: '__root__' | '/Folio'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  FolioRoute: typeof FolioRoute
}

const rootRouteChildren: RootRouteChildren = {
  FolioRoute: FolioRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/Folio"
      ]
    },
    "/Folio": {
      "filePath": "Folio.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
